export const LANGS = [
  { id: "en", label: "English" },
  { id: "yo", label: "Yoruba" },
  { id: "ha", label: "Hausa" },
];

export const ui = {
  en: {
    brand: "Sahara",
    brandTag: "Your rights, in your language.",
    home: "Home",
    rightsNav: "My rights",
    phrasesNav: "Sample phrases",
    aboutNav: "About",
    eyebrow: "Legal & public services",
    title: "What happens at first appearance?",
    lead: "Speak in English, Yoruba, Hausa, or a mix — Sahara turns your voice into a court-usable answer.",
    askTitle: "Ask a question",
    askLead: "Hold to speak or type. We’ll match your question to the right information and rights.",
    hold: "Hold to talk",
    release: "Release to send",
    listening: "Listening… release to send",
    sending: "Sending to Sahara…",
    typeHint: "Or type what you want to know",
    typePlaceholder: "They gave me a court date. What are my rights?",
    typeInstead: "Type instead if your mic is not working",
    send: "Ask",
    hear: "Hear the short answer",
    youSaid: "Sahara heard",
    ready: "Ready to listen",
    saharaReady: "Sahara is ready",
    expectTitle: "First appearance (arraignment) — What to expect",
    expectToday: "What happens today",
    rightsTitle: "Your rights",
    rightsLead: "You have rights in court. Here are the most important ones and what to say.",
    phrasesTitle: "Sample phrases",
    phrasesLead: "Use these when you’re speaking to a magistrate, interpreter, or Legal Aid.",
    language: "Language",
    languageHint: "Switch language to get the same information in Yoruba or Hausa.",
    phoneNote: "Works on your phone. Simple. Built for everyday Nigerian use.",
    aboutTitle: "About this guide",
    aboutLead: "This app explains first appearance in plain language. It is information, not a lawyer.",
    howTitle: "How it works",
    howSteps: [
      "Pick English, Yoruba, or Hausa.",
      "Hold the microphone and speak, or type a question.",
      "Sahara transcribes your voice on the server.",
      "You get the workflow, your rights, and phrases you can say.",
    ],
    seeAll: "See all",
    inPractice: "What often happens",
    sayThis: "What you can say",
    seeLawyer: "When to see a lawyer",
  },
  yo: {
    brand: "Sahara",
    brandTag: "Ẹ̀tọ́ rẹ, ní èdè rẹ.",
    home: "Ilé",
    rightsNav: "Ẹ̀tọ́ mi",
    phrasesNav: "Àwọn ọ̀rọ̀ àpẹẹrẹ",
    aboutNav: "Nípa",
    eyebrow: "Òfin àti iṣẹ́ ìjọba",
    title: "Kí ló ń ṣẹlẹ̀ ní ìfarahàn àkọ́kọ́?",
    lead: "Sọ̀rọ̀ ní Gẹ̀ẹ́sì, Yorùbá, Hausa, tàbí kí o dà wọ́n pọ̀ — Sahara yí ohùn rẹ sí ìdáhùn tí o lè lò nílé-ẹjọ́.",
    askTitle: "Béèrè ìbéèrè",
    askLead: "Tẹ̀ mọ́lẹ̀ láti sọ̀rọ̀ tàbí kọ. A ó so ìbéèrè rẹ pọ̀ mọ́ ẹ̀tọ́ tó yẹ.",
    hold: "Tẹ̀ mọ́lẹ̀ láti sọ̀rọ̀",
    release: "Fi sílẹ̀ láti fi ránṣẹ́",
    listening: "Ń gbọ́… fi sílẹ̀ láti fi ránṣẹ́",
    sending: "Ń fi sí Sahara…",
    typeHint: "Tàbí kọ ohun tí o fẹ́ mọ̀",
    typePlaceholder: "Wọ́n fún mi ní ọjọ́ ilé-ẹjọ́. Kí ni ẹ̀tọ́ mi?",
    typeInstead: "Kọ ọ̀rọ̀ tí gbohùngbohùn kò bá ṣiṣẹ́",
    send: "Béèrè",
    hear: "Gbọ́ ìdáhùn kúkúrú",
    youSaid: "Sahara gbọ́",
    ready: "Ó ṣetán láti gbọ́",
    saharaReady: "Sahara ṣetán",
    expectTitle: "Ìfarahàn àkọ́kọ́ — Ohun tí o lè retí",
    expectToday: "Kí ló ń ṣẹlẹ̀ lónìí",
    rightsTitle: "Ẹ̀tọ́ rẹ",
    rightsLead: "O ní ẹ̀tọ́ nílé-ẹjọ́. Àwọn wọ̀nyí ṣe pàtàkì, àti ohun tí o lè sọ.",
    phrasesTitle: "Àwọn ọ̀rọ̀ àpẹẹrẹ",
    phrasesLead: "Lo àwọn wọ̀nyí níwájú magistrate, interpreter, tàbí Legal Aid.",
    language: "Èdè",
    languageHint: "Yí èdè padà láti gba ìsọfúnni kan náà ní Yorùbá tàbí Hausa.",
    phoneNote: "Ó ń ṣiṣẹ́ lórí ẹ̀rọ ìbáraẹnisọ̀rọ̀ rẹ.",
    aboutTitle: "Nípa ìtọ́sọ́nà yìí",
    aboutLead: "Àpù yìí ń ṣàlàyé ìfarahàn àkọ́kọ́ ní èdè tó rọrùn. Àlàyé ni, kì í ṣe agbẹjọ́rò.",
    howTitle: "Bí ó ṣe ń ṣiṣẹ́",
    howSteps: [
      "Yan Gẹ̀ẹ́sì, Yorùbá, tàbí Hausa.",
      "Tẹ̀ mọ́lẹ̀ lórí gbohùngbohùn tàbí kọ ìbéèrè.",
      "Sahara yí ohùn rẹ sí ọ̀rọ̀.",
      "O ó rí ìlànà, ẹ̀tọ́ rẹ, àti ọ̀rọ̀ tí o lè sọ.",
    ],
    seeAll: "Wo gbogbo rẹ̀",
    inPractice: "Ohun tí sábà máa ń ṣẹlẹ̀",
    sayThis: "Ohun tí o lè sọ",
    seeLawyer: "Nígbà tí o yẹ kí o rí agbẹjọ́rò",
  },
  ha: {
    brand: "Sahara",
    brandTag: "Hakkin ka, a yaren ka.",
    home: "Gida",
    rightsNav: "Hakki na",
    phrasesNav: "Kalmomi na misali",
    aboutNav: "Game da",
    eyebrow: "Shari'a da sabis na jama'a",
    title: "Me ke faruwa a bayyanar farko?",
    lead: "Yi magana da Turanci, Yoruba, Hausa, ko gauraye — Sahara tana mayar da muryarka zuwa amsa da za ka yi amfani da ita a kotu.",
    askTitle: "Yi tambaya",
    askLead: "Riƙe don magana ko rubuta. Za mu daidaita tambayar ka da hakki da bayani.",
    hold: "Riƙe don magana",
    release: "Saki don aika",
    listening: "Ana saurare… saki don aika",
    sending: "Ana aikawa Sahara…",
    typeHint: "Ko rubuta abin da kake so",
    typePlaceholder: "An ba ni ranar kotu. Menene hakki na?",
    typeInstead: "Rubuta idan makirufo bai yi aiki ba",
    send: "Tambaya",
    hear: "Ji gajeren amsa",
    youSaid: "Sahara ta ji",
    ready: "A shirye don saurare",
    saharaReady: "Sahara a shirye take",
    expectTitle: "Bayyanar farko — Abin da za ka yi tsammani",
    expectToday: "Me ke faruwa yau",
    rightsTitle: "Hakkin ka",
    rightsLead: "Kana da hakki a kotu. Ga mafi muhimmanci da abin da za ka ce.",
    phrasesTitle: "Kalmomi na misali",
    phrasesLead: "Yi amfani da su sa’ad da kake magana da alkali, mai fassara, ko Legal Aid.",
    language: "Harshe",
    languageHint: "Canza harshe don samun wannan bayani a Yoruba ko Hausa.",
    phoneNote: "Yana aiki a wayarka.",
    aboutTitle: "Game da wannan jagora",
    aboutLead: "Wannan manhaja tana bayyana bayyanar farko a sauƙaƙe. Bayani ne, ba lauya ba.",
    howTitle: "Yadda yake aiki",
    howSteps: [
      "Zaɓi Turanci, Yoruba, ko Hausa.",
      "Riƙe makirufo ka yi magana, ko ka rubuta tambaya.",
      "Sahara tana juya murya zuwa rubutu.",
      "Za ka sami tsari, hakki, da kalmomin da za ka faɗa.",
    ],
    seeAll: "Duba duka",
    inPractice: "Abin da yakan faru",
    sayThis: "Abin da za ka iya cewa",
    seeLawyer: "Lokacin da ya kamata ka ga lauya",
  },
};
