export const LANGS = [
  { id: "en", label: "English", native: "English" },
  { id: "yo", label: "Yoruba", native: "Yorùbá" },
  { id: "ha", label: "Hausa", native: "Hausa" },
];

export const welcome = {
  titles: ["Welcome", "Ẹ káàbọ̀", "Barka da zuwa"],
  leads: [
    "Choose the language for this guide.",
    "Yan èdè fún ìtọ́sọ́nà yìí.",
    "Zaɓi harshen wannan jagora.",
  ],
  later: "You can change this later · O lè yí i padà · Za ka iya canza daga baya.",
};

export const ui = {
  en: {
    brand: "Sahara",
    brandTag: "Your rights, in your language.",
    home: "Home",
    rightsNav: "My rights",
    phrasesNav: "Sample phrases",
    aboutNav: "About",
    eyebrow: "Legal & public services",
    title: "What happens at first appearance?",
    lead: "Speak in English, Yoruba, Hausa, or a mix — Sahara turns your voice into a court-usable answer.",
    askTitle: "Ask a question",
    askLead: "Hold to speak or type. We’ll match your question to the right information and rights.",
    hold: "Hold to talk",
    release: "Release to send",
    listening: "Listening… release to send",
    sending: "Sending to Sahara…",
    typeHint: "Or type what you want to know",
    typePlaceholder: "They gave me a court date. What are my rights?",
    typeInstead: "Type instead if your mic is not working",
    send: "Ask",
    hear: "Hear the short answer",
    hearBusy: "Getting the voice…",
    playing: "Playing…",
    tapPlay: "If you hear nothing, tap play below.",
    youSaid: "Sahara heard",
    ready: "You can talk now",
    saharaReady: "You can talk now",
    expectTitle: "What to expect",
    expectToday: "What happens today",
    expectOne: "The charge is read. You enter a plea. Bail may be decided.",
    rightsTitle: "Your rights",
    rightsLead: "You have rights in court. Here are the most important ones and what to say.",
    rightsOne: "Interpreter, lawyer, silence, and bail — and what you can say.",
    phrasesTitle: "Sample phrases",
    phrasesLead: "Use these when you’re speaking to a magistrate, interpreter, or Legal Aid.",
    phrasesOne: "Short lines to say to a magistrate, interpreter, or Legal Aid.",
    seeMore: "See more",
    language: "Language",
    languageHint: "Switch language to get the same information in Yoruba or Hausa.",
    phoneNote: "Works on your phone. Simple. Built for everyday Nigerian use.",
    aboutTitle: "About this guide",
    aboutLead: "This app explains first appearance in plain language. It is information, not a lawyer.",
    howTitle: "How it works",
    howSteps: [
      "Pick English, Yoruba, or Hausa.",
      "Hold the microphone and speak, or type a question.",
      "Sahara transcribes your voice on the server.",
      "You get the workflow, your rights, and phrases you can say.",
    ],
    seeAll: "See all",
    tapToRead: "Tap to read",
    hideDetail: "Hide",
    morePhrases: "More lines",
    inPractice: "What often happens",
    sayThis: "What you can say",
    seeLawyer: "When to see a lawyer",
  },
  yo: {
    brand: "Sahara",
    brandTag: "Ẹ̀tọ́ rẹ, ní èdè rẹ.",
    home: "Ilé",
    rightsNav: "Ẹ̀tọ́ mi",
    phrasesNav: "Àwọn ọ̀rọ̀ àpẹẹrẹ",
    aboutNav: "Nípa",
    eyebrow: "Òfin àti iṣẹ́ ìjọba",
    title: "Kí ló ń ṣẹlẹ̀ ní ìfarahàn àkọ́kọ́?",
    lead: "Sọ̀rọ̀ ní Gẹ̀ẹ́sì, Yorùbá, Hausa, tàbí kí o dà wọ́n pọ̀ — Sahara yí ohùn rẹ sí ìdáhùn tí o lè lò nílé-ẹjọ́.",
    askTitle: "Béèrè ìbéèrè",
    askLead: "Tẹ̀ mọ́lẹ̀ láti sọ̀rọ̀ tàbí kọ. A ó so ìbéèrè rẹ pọ̀ mọ́ ẹ̀tọ́ tó yẹ.",
    hold: "Tẹ̀ mọ́lẹ̀ láti sọ̀rọ̀",
    release: "Fi sílẹ̀ láti fi ránṣẹ́",
    listening: "Ń gbọ́… fi sílẹ̀ láti fi ránṣẹ́",
    sending: "Ń fi sí Sahara…",
    typeHint: "Tàbí kọ ohun tí o fẹ́ mọ̀",
    typePlaceholder: "Wọ́n fún mi ní ọjọ́ ilé-ẹjọ́. Kí ni ẹ̀tọ́ mi?",
    typeInstead: "Kọ ọ̀rọ̀ tí gbohùngbohùn kò bá ṣiṣẹ́",
    send: "Béèrè",
    hear: "Gbọ́ ìdáhùn kúkúrú",
    hearBusy: "Ń gba ohùn…",
    playing: "Ń gbọ́…",
    tapPlay: "Tí o kò bá gbọ́ nkankan, tẹ̀ play nísàlẹ̀.",
    youSaid: "Sahara gbọ́",
    ready: "O lè sọ̀rọ̀ nísinsìnyí",
    saharaReady: "O lè sọ̀rọ̀ nísinsìnyí",
    expectTitle: "Ohun tí o lè retí",
    expectToday: "Kí ló ń ṣẹlẹ̀ lónìí",
    expectOne: "Wọn yóò ka ẹ̀sùn. O ó jẹ́wọ́. Wọn lè pinnu bail.",
    rightsTitle: "Ẹ̀tọ́ rẹ",
    rightsLead: "O ní ẹ̀tọ́ nílé-ẹjọ́. Àwọn wọ̀nyí ṣe pàtàkì, àti ohun tí o lè sọ.",
    rightsOne: "Olùtumọ̀, agbẹjọ́rò, ìdákẹ́jẹ́, àti bail — àti ohun tí o lè sọ.",
    phrasesTitle: "Àwọn ọ̀rọ̀ àpẹẹrẹ",
    phrasesLead: "Lo àwọn wọ̀nyí níwájú magistrate, interpreter, tàbí Legal Aid.",
    phrasesOne: "Ọ̀rọ̀ kúkúrú tí o lè sọ níwájú adájọ́ tàbí Legal Aid.",
    seeMore: "Wo síwájú",
    language: "Èdè",
    languageHint: "Yí èdè padà láti gba ìsọfúnni kan náà ní Yorùbá tàbí Hausa.",
    phoneNote: "Ó ń ṣiṣẹ́ lórí ẹ̀rọ ìbáraẹnisọ̀rọ̀ rẹ.",
    aboutTitle: "Nípa ìtọ́sọ́nà yìí",
    aboutLead: "Àpù yìí ń ṣàlàyé ìfarahàn àkọ́kọ́ ní èdè tó rọrùn. Àlàyé ni, kì í ṣe agbẹjọ́rò.",
    howTitle: "Bí ó ṣe ń ṣiṣẹ́",
    howSteps: [
      "Yan Gẹ̀ẹ́sì, Yorùbá, tàbí Hausa.",
      "Tẹ̀ mọ́lẹ̀ lórí gbohùngbohùn tàbí kọ ìbéèrè.",
      "Sahara yí ohùn rẹ sí ọ̀rọ̀.",
      "O ó rí ìlànà, ẹ̀tọ́ rẹ, àti ọ̀rọ̀ tí o lè sọ.",
    ],
    seeAll: "Wo gbogbo rẹ̀",
    tapToRead: "Tẹ̀ láti kà á",
    hideDetail: "Fi pamọ́",
    morePhrases: "Ọ̀rọ̀ síwájú",
    inPractice: "Ohun tí sábà máa ń ṣẹlẹ̀",
    sayThis: "Ohun tí o lè sọ",
    seeLawyer: "Nígbà tí o yẹ kí o rí agbẹjọ́rò",
  },
  ha: {
    brand: "Sahara",
    brandTag: "Hakkin ka, a yaren ka.",
    home: "Gida",
    rightsNav: "Hakki na",
    phrasesNav: "Kalmomi na misali",
    aboutNav: "Game da",
    eyebrow: "Shari'a da sabis na jama'a",
    title: "Me ke faruwa a bayyanar farko?",
    lead: "Yi magana da Turanci, Yoruba, Hausa, ko gauraye — Sahara tana mayar da muryarka zuwa amsa da za ka yi amfani da ita a kotu.",
    askTitle: "Yi tambaya",
    askLead: "Riƙe don magana ko rubuta. Za mu daidaita tambayar ka da hakki da bayani.",
    hold: "Riƙe don magana",
    release: "Saki don aika",
    listening: "Ana saurare… saki don aika",
    sending: "Ana aikawa Sahara…",
    typeHint: "Ko rubuta abin da kake so",
    typePlaceholder: "An ba ni ranar kotu. Menene hakki na?",
    typeInstead: "Rubuta idan makirufo bai yi aiki ba",
    send: "Tambaya",
    hear: "Ji gajeren amsa",
    hearBusy: "Ana samun murya…",
    playing: "Ana kunna…",
    tapPlay: "Idan ba ka ji komai ba, taɓa play a ƙasa.",
    youSaid: "Sahara ta ji",
    ready: "Za ka iya magana yanzu",
    saharaReady: "Za ka iya magana yanzu",
    expectTitle: "Abin da za ka yi tsammani",
    expectToday: "Me ke faruwa yau",
    expectOne: "Za a karanta tuhumar. Za ka amsa. Za a iya yanke hukuncin beli.",
    rightsTitle: "Hakkin ka",
    rightsLead: "Kana da hakki a kotu. Ga mafi muhimmanci da abin da za ka ce.",
    rightsOne: "Mai fassara, lauya, shiru, da beli — da abin da za ka ce.",
    phrasesTitle: "Kalmomi na misali",
    phrasesLead: "Yi amfani da su sa’ad da kake magana da alkali, mai fassara, ko Legal Aid.",
    phrasesOne: "Gajerun kalmomi da za ka faɗa wa alkali ko Legal Aid.",
    seeMore: "Duba ƙari",
    language: "Harshe",
    languageHint: "Canza harshe don samun wannan bayani a Yoruba ko Hausa.",
    phoneNote: "Yana aiki a wayarka.",
    aboutTitle: "Game da wannan jagora",
    aboutLead: "Wannan manhaja tana bayyana bayyanar farko a sauƙaƙe. Bayani ne, ba lauya ba.",
    howTitle: "Yadda yake aiki",
    howSteps: [
      "Zaɓi Turanci, Yoruba, ko Hausa.",
      "Riƙe makirufo ka yi magana, ko ka rubuta tambaya.",
      "Sahara tana juya murya zuwa rubutu.",
      "Za ka sami tsari, hakki, da kalmomin da za ka faɗa.",
    ],
    seeAll: "Duba duka",
    tapToRead: "Taɓa don karantawa",
    hideDetail: "Ɓoye",
    morePhrases: "Kara kalmomi",
    inPractice: "Abin da yakan faru",
    sayThis: "Abin da za ka iya cewa",
    seeLawyer: "Lokacin da ya kamata ka ga lauya",
  },
};
